#pragma once

#define MSV1_0_CREDENTIAL_KEY_LENGTH 20
#define MSV1_0_CHALLENGE_LENGTH 8
#define MSV1_0_RESPONSE_LENGTH 24
#define MSV1_0_NTLM3_RESPONSE_LENGTH 16
#define MSV1_0_USER_SESSION_KEY_LENGTH 16
#define MSV1_0_NT_OWF_PASSWORD_LENGTH 16
#define MSV1_0_LM_OWF_PASSWORD_LENGTH 16
#define MSV1_0_SHA_OWF_PASSWORD_LENGTH 20